// ---------------------------------------------------------------------------
// PER-SITE CONFIG - the only JS file you edit to fork this to another product.
// Loaded before script.js. For the static HTML/asset swaps (title, FAQ, brand,
// favicon, Stripe link, Brevo form), see FORK.md - those live in index.html.
// ---------------------------------------------------------------------------
window.SITE = {
  product: "Codex",
  // Who runs the status page. Used when a vendor-wide incident doesn't touch any
  // of our scoped components ("...but OpenAI is reporting a wider incident").
  vendor: "OpenAI",

  // OpenAI public Statuspage feed.
  statusUrl: "https://status.openai.com/api/v2/summary.json",

  copy: {
    // up.sublines is picked at random each render — keep them in-character.
    up: {
      verdict: "YES",
      sublines: [
        "Codex is up. Back to work.",
        "Codex is up. No more excuses.",
        "Codex is up. Touch grass later.",
        "Codex is up. The vibes are compiling again.",
        "Codex is up. Your roadmap is no longer folklore.",
        "Codex is up. Close the other 14 tabs.",
        "Codex is up. Standup is saved.",
        "Codex is up. You may stop refreshing now.",
        "Codex is up. Cancel the Stack Overflow pilgrimage.",
        "Codex is up. Tell Claude it was nothing personal.",
        "Codex is up. Put Gemini back in the drawer.",
        "Codex is up. Your keyboard has purpose again.",
        "Codex is up. The human-in-the-loop is off duty.",
        "Codex is up. Resume vibe coding immediately.",
        "Codex is up. Crisis averted, deploy with confidence.",
        "Codex is up. Pretend the panic never happened.",
        "Codex is up. Your impostor syndrome can stand down.",
        "Codex is up. Ship the thing you were one prompt away from.",
        "Codex is up. Antigravity can wait for someone else.",
        "Codex is up. Go be a 10x engineer again.",
        "Codex is up. The git blame points back at you now.",
        "Codex is up. Your rubber duck is off the hook.",
        "Codex is up. Ship it and find out.",
        "Codex is up. Reopen all 14 tabs with confidence.",
        "Codex is up. Your sprint is back from the dead.",
        "Codex is up. Autocomplete your way to glory.",
        "Codex is up. The agent is agentic once more.",
        "Codex is up. Refactor everything, regret nothing.",
        "Codex is up. Your TODO list looks nervous again.",
        "Codex is up. Token budget: cautiously optimistic.",
        "Codex is up. The terminal missed you too.",
        "Codex is up. The CLI breathes again.",
        "Codex is up. Tell Cursor it can sit back down.",
        "Codex is up. Tibo smiled upon us today.",
        "Codex is up. Merge with reckless confidence.",
        "Codex is up. Promote yourself back to 10x.",
        "Codex is up. The autocomplete autocompletes once more.",
        "Codex is up. Go ship something you'll regret on Friday.",
        "Codex is up. Alex Albert can go back to his own timeline.",
        "Codex is up. Uninstall the backup CLI. Or don't. We won't tell.",
        "Codex is up. Your subagents are back on the payroll.",
      ],
      subline: "Codex is up. Back to work.",
    },
    degraded: {
      verdict: "KINDA",
      subline: "Some Codex components are degraded.",
      // shown when no specific component is named — keep it in-character.
      sublines: [
        "Codex is having a moment. Breathe.",
        "It's not down, it's 'reasoning'.",
        "Partial outage, full panic. Standard.",
        "Codex is mostly here, spiritually elsewhere.",
        "Some components are vibing inconsistently.",
        "Degraded: like your sleep schedule.",
        "Half a Codex is better than no Codex. Allegedly.",
        "Running on vibes and a flaky connection.",
      ],
    },
    down: {
      verdict: "NO",
      subline: "Codex is having a rough time.",
      sublines: [
        "Codex is down. This is not a drill, but it is a refresh.",
        "Codex is down. Touch grass, allegedly.",
        "Codex is down. The vibes have stopped compiling.",
        "Codex is down. Your keyboard is now decorative.",
        "Codex is down. Somewhere, Stack Overflow is smiling.",
        "Codex is down. Initiate manual reasoning protocol.",
        "Codex is down. Time to become the intelligence yourself.",
        "Codex is down. The roadmap is folklore again.",
      ],
    },
    unreachable: "Can't even reach the status page. That's rarely a good sign.",
  },

  // Sponsor rail placements, rendered by rails.js into the two fixed corner
  // rails. The final card in the right rail is always the visually distinct
  // "Advertise here" offer, even when house sponsors are configured.
  //
  //   { name: "Acme", blurb: "Ship faster.", url: "https://acme.dev",
  //     logo: "assets/acme.png" }   // logo optional, falls back to the initial
  //
  // Entries need both `name` and `url` or they are skipped. Links are emitted
  // rel="sponsored noopener" so a paid placement never passes ranking signal.
  sponsors: [
    {
      name: "Atlas Quest",
      blurb: "Free world geography games for your next five-minute break.",
      url: "https://atlas.snackpackuniverse.com/",
      logo: "assets/atlas-quest-mark.svg",
    },
  ],


  // OpenAI exposes ~25 services. This site's YES/NO verdict is scoped to the
  // Codex-relevant ones rather than the global OpenAI indicator.
  //
  // ⚠ THESE STRINGS MUST MATCH OpenAI'S PUBLISHED COMPONENT NAMES EXACTLY (case-insensitive).
  // They are not ours to choose — OpenAI renames and retires components without notice.
  // A previous list ("Codex API", "CLI", "VS Code extension") matched NOTHING Codex-related,
  // so the verdict was silently computed from Login + Realtime alone for months.
  //
  // To re-check the live names before editing:
  //   curl -s https://status.openai.com/api/v2/summary.json | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>JSON.parse(s).components.forEach(c=>console.log(c.name)))"
  //
  // As published on 2026-08-06:
  //   Images, Sites, Responses, Codex in ChatGPT Desktop, Login, Audio, Login,
  //   Compliance API, Files, FedRAMP, Ads Manager, Conversations, Search, Sora,
  //   Ads API, Fine-tuning, ChatGPT Atlas, Deep Research, Image Generation, Agent,
  //   Realtime, Voice mode, Batch, Embeddings, Moderations
  //
  // (Note "Login" appears TWICE, under two different groups — script.js collapses
  // duplicate names, keeping the worse status of the pair.)
  components: {
    statusSource: "components",
    include: [
      "Codex in ChatGPT Desktop", // the only literally-Codex component OpenAI publishes
      "Responses",                // the API surface the Codex CLI/extension calls
      "Login",                    // no auth, no Codex
    ],
    limit: 8,
  },

  robots:  {
    up: "assets/codex-status-up-online-green-transparent.webp",
    degraded: "assets/codex-status-unknown-yellow-transparent.webp",
    down: "assets/codex-status-down-offline-red-transparent.webp",
  },
  buttons: {
    up: "assets/codex-button-green-transparent.webp",
    down: "assets/codex-button-red-transparent.webp",
    default: "assets/codex-button-yellow-transparent.webp",
  },

  quotes: [
    "Codex is down? Can't wait for a free usage reset from Tibo.",
    "Codex, solve downtime issues, make no mistakes.",
    "Codex needs to return before my boss notices my productivity is at zero.",
    "I'm actually considering Cursor. What have I become?",
    "I was close to breaking a world record prompt run. Now I need another billion tokens.",
    "My assignment is due tomorrow and I just started.",
    "If Codex goes down, so does my productivity.",
    "I forgot how to code without it.",
    "Refreshing this page is my whole personality now.",
    "It was working FINE thirty seconds ago.",
    "I have 14 tabs of half-finished prompts.",
    "Please. I was so close.",
    "My standup is in 10 minutes and I have nothing.",
    "Switching to Stack Overflow like it's 2015.",
    "I will touch grass the moment it's back. Not before.",
    "Have you tried turning the AI off and on again?",
    "This is the longest 4 minutes of my life.",
    "I'm thinking of using Antigravity. Look what you made me do.",
    "What's the URL for Claude again?",
    "Does this mean we get another usage reset?",
    "Guess I'll go open Cursor. Ugh.",
    "Copilot it is, then. May God have mercy.",
    "I'd ask Claude but I have my dignity.",
    "Is it down for everyone or just me being punished?",
    "My rate limit reset 3 minutes ago and now THIS.",
    "Codex needs to come back before my boss notices I am just rearranging tabs.",
    "I was one prompt away from shipping. That prompt was doing a lot of work.",
    "The outage began exactly when I typed 'one last thing'. Suspicious.",
    "I am about to read the documentation myself. Nobody wants that.",
    "This is not downtime. This is forced independent thinking.",
    "Refresh. Pray. Repeat.",
    "Five nines of uptime and all nine went missing at once.",
    "Status: for once, it's not me, it's you.",
    "Tried Copilot. It autocompleted my resignation letter.",
    "Antigravity? With a name like that, no wonder nothing's holding up.",
    "Grok is right there. So is my self-respect.",
    "I'd switch to Gemini, but only in incognito.",
    "Devin can't take my job while Codex is down too. Small mercies.",
    "Turns out my '10x engineer' was just an API key.",
    "git blame says it's the outage. Finally, not me.",
    "I'm the autocomplete now, and it's going poorly.",
    "My agent is, tragically, agentless.",
    "Told my PM it's an 'upstream dependency'. Technically true.",
    "Standup update: blocked. Spiritually and literally.",
    "My rubber duck just got promoted back to senior dev.",
    "Asked ChatGPT if Codex was down. It said 'as an AI…'.",
    "The terminal is cold and quiet without you, Codex.",
    "I've forgotten every keyboard shortcut except F5.",
    "My productivity chart just discovered the x-axis.",
    "Cursor, Windsurf, Copilot — it's giving rebound relationship.",
    "My productivity graph is now just a cliff with Wi-Fi.",
    "I asked for a quick fix, not a character-building exercise.",
    "I have reached the bargaining stage of prompt dependency.",
    "Somewhere, a usage reset timer is laughing at me.",
    "If this counts against my limit, I am writing a strongly worded prompt.",
    "I did not budget emotionally for manual reasoning today.",
    "The fallback plan was 'ask Codex again' and I stand by it.",
    "Gemini is looking at me like it has been waiting for this moment.",
    "Google, put the Antigravity down. This is already unstable.",
    "I opened Gemini and immediately apologized to my workflow.",
    "I considered Cursor for three seconds and need a shower.",
    "Copilot just said 'we can try'. That is not the energy I need.",
    "If Codex is down, my keyboard is basically decorative.",
    "I am not procrastinating. I am monitoring critical infrastructure.",
    "The incident report better include my lost vibe.",
    "I can stop refreshing anytime. I simply choose not to.",
    "The status page says operational, but my soul says degraded.",
    "Codex is up? Great. I have forgotten what I was doing.",
    "I was promised artificial intelligence, not artificial patience.",
    "This is why I keep a backup AI and never respect it.",
    "My prompt was too powerful. The servers needed a minute.",
    "Codex went down and took my plausible deniability with it.",
    "I am one outage away from naming variables myself.",
    "If the next reset is free, I forgive everything.",
    "I asked Codex to improve uptime and it scheduled a personal day.",
    "This is the kind of downtime that makes a person install another CLI.",
    "My TODO list just made eye contact with me.",
    "I have become the human in the loop. Horrifying.",
    "Codex is down and somehow my impostor syndrome is up.",
    "Every refresh is a tiny incident response drill.",
    "The only thing operational right now is my panic counter.",
    "I am going to write code unaided, like a historical reenactment.",
    "If anyone asks, I am doing resilience testing.",
    "My vibe coding has become vibe waiting.",
    "The vibes are not compiling.",
    "I was vibe coding. Now I am just vibing incorrectly.",
    "Codex is down and my roadmap just became folklore.",
    "My sprint velocity is now measured in refreshes per minute.",
    "I need Codex back before Jira develops opinions.",
    "This outage has promoted me to senior prompt engineer of nothing.",
    "I had a perfect prompt chain and now it is a cold case.",
    "I asked for agentic coding, not agentic abandonment.",
    "Claude is looking useful right now, which is how you know things are bad.",
    "Claude Code, if you can hear me, pretend this never happened.",
    "Do I open Claude or wait like a loyal fool?",
    "Codex is down. Claude is typing 'new phone who dis'.",
    "I would ask Claude, but I am emotionally unavailable.",
    "If Claude is up, please do not tell my Codex workflow.",
    "Gemini just sent a 'you up?' notification.",
    "Google saw me open Antigravity and immediately filed an incident.",
    "Antigravity sounds tempting until gravity comes back online.",
    "Gemini can help, but can it judge my messy repo with kindness?",
    "I am one outage away from becoming a multi-model household.",
    "The usage reset better come with an apology basket.",
    "If downtime burns tokens, I am invoicing the cloud.",
    "My rate limit has recovered faster than I have.",
    "Usage resets are just loot boxes for tired developers.",
    "I hit the button again for science and emotional support.",
    "This is not a bug. It is a productivity-denial service attack.",
    "My boss thinks I am blocked by dependencies. Technically true.",
    "The only dependency failing is me.",
    "I just renamed a variable manually and felt something leave my body.",
    "Stack Overflow opened and asked where I have been.",
    "I am reading the error message myself. Dark times.",
    "The AI is down, so now I have to be the intelligence.",
    "My commit message is going to be 'fixed during outage, somehow'.",
    "I trusted the agent with my flow state and it took PTO.",
    "This button is cheaper than therapy and less effective.",
    "Codex, blink twice if the context window ate the server.",
    "Somewhere in a data center, my half-written regex is alone.",
    "I am not saying Codex caused the outage, but I did ask it to refactor everything.",
    "Codex is down and my vibe-coded masterpiece is now just vibes.",
    "The agent stopped mid-task and left me holding the diff.",
    "I need a usage reset and a personal reset.",
    "If this outage lasts any longer, I might understand my own code.",
    "Somewhere, Tibo is not refunding my emotional tokens.",
    "I opened the terminal and it looked back disappointed.",
    "My AI pair programmer has gone for a long lunch.",
    "Codex paused at 99 percent confidence and zero percent uptime.",
    "This is why I never delete the TODO comments.",
    "Manual coding? In this economy?",
    "Antigravity sounds fun until your stack trace starts floating.",
    "Gemini said it can help, which is exactly what worries me.",
    "Claude is my backup plan, and I hate that this is growth.",
    "Cursor just cleared its throat from the dock.",
    "I was one autonomous step away from blaming the agent.",
    "Refreshing Tibo's timeline harder than I refresh this page.",
    "Tibo, this is your sign to announce a usage reset.",
    "My emotional support account is Tibo's Twitter.",
    "Somewhere, Tibo is drafting the tweet that fixes my whole day.",
    "I don't need a therapist, I need Tibo to tweet 'limits reset'.",
    "Checking Tibo's mentions for hope like it's a status page.",
    "Tibo posts a reset and suddenly I believe in something again.",
    "I told my manager the AI was down and they said 'so do it yourself' like that's a real option.",
    "Plot twist: I was the large language model all along.",
    "Loading… loading… still loading… this is the content now.",
    "404: motivation not found while Codex is down.",
    "My code works on my machine, but only when Codex works on its machine.",
    "It's giving 'temporarily a junior developer again'.",
    "Pair programming, but my pair ghosted me mid-function.",
    "I'm not stuck, I'm pre-productive.",
    "The real outage was the dependencies we added along the way.",
    "Codex down? Bold of the universe to assume I have a plan B.",
    "I miss you like a missing semicolon misses its line.",
    "Currently bargaining with a status page like it can hear me.",
    "Me: one more prompt. Codex: 503. Me: I suppose I deserve this.",
    "Outage speedrun, any%: refreshing as fast as humanly possible.",
    "My flow state has filed a missing person report.",
    "We don't say 'I can't code', we say 'my AI is experiencing an incident' and we leave.",
    "This is the villain origin story for someone who writes their own functions.",
    "I asked it to make me a 10x engineer and it made me wait 10x longer.",
    "Schrödinger's deploy: it both ships and doesn't until Codex returns.",
    "I'd read the docs, but I've forgotten how to read since 2023.",
    "Tell my Jira tickets I love them.",
    "The only thing scaling right now is my anxiety.",
    "Brb, googling 'how to code' unironically.",
    "If you need me I'll be staring at this spinner like it owes me money.",
    "Downtime is just the universe code-reviewing my life choices.",
    "I have entered the 'maybe I'll write tests' stage of grief.",
    "My standup status: 'AI is down' is technically a blocker, Brenda.",
    "It's quiet. Too quiet. The autocomplete hasn't autocompleted in minutes.",
    "I came here to vibe code and chew bubblegum, and the servers are out of both.",
    "My prompt history is the only proof I ever knew how to do this job.",
    "I was today years old when I remembered I'm the senior engineer here.",
    "The agent stopped, the cursor blinks, and the abyss blinks back.",
    "I'm one outage away from reading my own stack trace like a fortune teller.",
    "Productivity is temporary. The smash button is forever.",

    // --- The rival camp's public face. Alex Albert is Anthropic's developer-relations
    // lead; isclaudeup ribs Tibo the same way. Keep these AFFECTIONATE and about the
    // narrator's own paranoia — never put words or actions in a real person's mouth. ---
    "Codex is down and Alex Albert has never been more insufferable.",
    "Somewhere, Alex Albert is enjoying this far too much.",
    "If I open Claude now, Alex Albert wins. I refuse.",
    "Alex Albert's timeline is suspiciously cheerful this morning.",
    "I'd defect to the Claude side, but I'd have to learn a whole new CLI.",
    "Do not let Alex Albert see the panic counter.",
    "I will not give Alex Albert the satisfaction. I will simply sit here.",
    "Alex Albert is out there shipping and I am out here refreshing.",

    // --- The switching cluster: leaving in shame, coming back pretending it never happened. ---
    "Switching to Claude 'just for today'. That's what they all say.",
    "I installed Claude Code during the last outage and never quite uninstalled it.",
    "My loyalty lasts exactly as long as the outage does.",
    "Every outage makes me five percent more multi-model.",
    "I'm not switching, I'm diversifying.",
    "Came back the second it was up. Claude will never know.",
    "I keep Claude Code installed the way you keep a spare tyre.",
    "The switching cost is emotional, not technical.",
    "Two CLIs, one keyboard, zero loyalty.",
    "I ran the same prompt in Claude out of spite. It was fine. That's worse.",
    "If it's down again tomorrow I'm switching, and we both know I'm lying.",
    "I have a backup subscription for exactly this scenario and I resent it.",
    "Nothing radicalises a developer like four minutes of downtime.",
    "I'm one more outage from a very awkward conversation with my ChatGPT plan.",

    // --- Agent-era material: the workflow is bigger than one chat box now. ---
    "My subagents are sitting there, unemployed.",
    "The MCP servers are up. Nothing to serve them to.",
    "The agent opened forty PRs and then vanished. Classic.",
    "Turns out 'autonomous' still requires the servers to be switched on.",
    "I finally have time to read what the agent actually did last week. Regrets.",
    "Context compaction hit, and then so did the outage.",
    "I reviewed a diff by hand today. I need a moment.",
    "My whole workflow is one API away from being a hobby.",
    "Rate limits I can plan around. Absence is harder.",
    "DeepSeek is one tab away and I am being very strong about this.",
    "Kimi and Qwen are apparently having a wonderful day.",
    "Mistral said bonjour and I nearly caved.",
    "The orchestrator has nothing to orchestrate.",
    "Somewhere a cron job is still cheerfully firing into the void.",
  ],
};
